import { Download, ExternalLink, Gamepad2, Hand, Info, Keyboard, MousePointer2, Orbit, Volume2 } from 'lucide-react';
import { Modal } from './Modal';
import { useStore } from '../state';
import { qualityNames, type QualitySetting } from '../performance/quality';
import { playSound } from '../audio/sounds';

export function Help() {
  return <Modal title="Sua aventura começa aqui"><p className="modal-intro">Você é o piloto! Não precisa saber tudo: vamos descobrir juntos.</p><div className="help-step"><span>1</span><div><h3>Escolha sua próxima parada</h3><p>Toque em um planeta no espaço ou abra a lista de astros. Use “Visitar de perto” para explorar suas luas.</p></div></div><div className="help-step"><span>2</span><div><h3>Brinque com o tempo</h3><p>Experimente os 5 botões da máquina do tempo. Os níveis 1 e 2 ajudam a observar a rotação; 3 mostra as luas; 4 e 5 aceleram as viagens dos planetas.</p></div></div><div className="help-step"><span>3</span><div><h3>Descubra e conquiste estrelas</h3><p>Visite mundos e acerte desafios de nomes. Use as pistas! Seu passaporte guarda suas descobertas neste aparelho.</p></div></div><div className="help-controls"><div><MousePointer2 size={20} /><strong>No computador</strong><p>Arraste para olhar. Use a roda para aproximar. Arraste com o botão direito para mover o centro.</p></div><div><Hand size={20} /><strong>No tablet ou celular</strong><p>Arraste com um dedo para olhar. Abra ou feche dois dedos para aproximar. Arraste com dois dedos para mover.</p></div></div><div className="keyboard-help"><Keyboard size={18} /><span><kbd>Espaço</kbd> pausar · <kbd>1</kbd>–<kbd>5</kbd> velocidade · <kbd>Home</kbd> início · <kbd>+</kbd>/<kbd>−</kbd> zoom</span></div><div className="scale-explanation"><Orbit size={20} /><div><h3>Um universo que cabe na tela</h3><p>Os tamanhos e as distâncias têm escalas educativas diferentes. A visão geral aproxima os planetas. A visão local amplia o planeta e separa suas luas. Na visita a uma lua, ela é ampliada novamente.</p><p>Rotação é girar em torno de si mesmo. Translação é dar uma volta ao redor de outro astro. Os períodos são reais e compartilham o mesmo relógio.</p><p>As elipses são uma simulação simplificada, sem a atração entre todos os corpos. A posição inicial se baseia em J2000; este jogo não mostra o céu de hoje. No modo local, a luz vem de uma direção fixa para ajudar a enxergar a superfície, sem reproduzir fases e eclipses.</p></div></div><button className="primary-button full-width" onClick={() => useStore.getState().setModal(null)}><Gamepad2 size={19} /> Entendi. Vamos explorar!</button></Modal>;
}

export function Settings({ install, installable, offlineReady }: { install: () => void; installable: boolean; offlineReady: boolean }) {
  const quality = useStore(s => s.quality), autoQuality = useStore(s => s.autoQuality), sound = useStore(s => s.sound), renderer = useStore(s => s.renderer), rendererActive = useStore(s => s.rendererActive);
  return <Modal title="Do seu jeitinho"><p className="modal-intro">Ajuste sua nave para uma viagem confortável.</p><label className="setting-field"><span>Qualidade da imagem<small>O modo automático se adapta ao aparelho e à fluidez.</small></span><select value={quality} onChange={e => useStore.getState().setQuality(e.target.value as QualitySetting)}>{Object.entries(qualityNames).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><p className="setting-caption">Em uso: {qualityNames[quality === 'auto' ? autoQuality : quality]} · resolução limitada para economizar bateria.</p><div className="setting-field"><span><Volume2 size={17} /> Sons de descoberta<small>Sons suaves ao responder aos desafios.</small></span><button role="switch" aria-label="Sons de descoberta" aria-checked={sound} className={`toggle ${sound ? 'on' : ''}`} onClick={() => { useStore.setState({ sound: !sound }); playSound('success', !sound); }}><i /></button></div><label className="setting-field"><span>Renderização<small>WebGL é o padrão. WebGPU é experimental e opcional.</small></span><select value={renderer} onChange={e => useStore.setState({ renderer: e.target.value as 'webgl' | 'webgpu' })}><option value="webgl">WebGL · compatível</option><option value="webgpu" disabled={!('gpu' in navigator)}>WebGPU · experimental</option></select></label><p className="setting-caption">Ativo: {rendererActive}. Se WebGPU não iniciar, o jogo usa WebGL.</p><div className="install-panel"><Download size={25} /><h3>Leve o universo com você</h3><p>Instale o Órbita na tela inicial e jogue como um aplicativo.</p>{installable ? <button className="primary-button" onClick={install}>Instalar Órbita</button> : <p className="install-instructions">No Android ou Chrome: menu ⋮ → Instalar aplicativo.<br />No iPad ou iPhone: Compartilhar → Adicionar à Tela de Início.</p>}<span className={offlineReady ? 'offline-state ready' : 'offline-state'}>{offlineReady ? '✓ Conteúdo pronto para jogar offline' : 'O conteúdo offline fica pronto após o primeiro carregamento completo da versão publicada.'}</span></div><div className="privacy-note"><Info size={18} /><p>Sem contas, anúncios ou banco de dados. Seu progresso fica só neste navegador. Se os dados do site forem apagados, o passaporte também será.</p></div><button className="text-button" onClick={() => useStore.getState().setModal('credits')}>Fontes, créditos e como a simulação funciona <ExternalLink size={15} /></button></Modal>;
}

export function Credits() {
  return <Modal title="Uma aventura com ciência"><div className="credits-content"><h3>Dados astronômicos</h3><p>Elementos orbitais de referência J2000: <a href="https://ssd.jpl.nasa.gov/planets/approx_pos.html" target="_blank" rel="noreferrer">NASA / JPL Solar System Dynamics</a>. Períodos, diâmetros e curiosidades: <a href="https://science.nasa.gov/solar-system/" target="_blank" rel="noreferrer">NASA Science</a> e <a href="https://ssd.jpl.nasa.gov/sats/elem/" target="_blank" rel="noreferrer">JPL, satélites naturais</a>. Valores arredondados para uso educativo.</p><h3>Texturas dos planetas, Sol e Lua</h3><p><a href="https://edu.solarsystemscope.com/textures/" target="_blank" rel="noreferrer">Solar System Scope / INOVE</a>, com base em imagens e dados NASA. Licença <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noreferrer">Creative Commons Atribuição 4.0</a>. Adaptadas em resolução e compressão WebP e KTX2/Basis. Os mapas possuem ajustes de cor e algumas regiões reconstruídas.</p><h3>Modelos e ilustrações</h3><p>Asteroide original gerado para o Órbita em GLB com compressão Meshopt. Luas além da Lua da Terra usam cores ilustrativas e esferas simplificadas, inclusive Fobos e Deimos, que são irregulares. Ícones Lucide: licença ISC. Símbolos e emojis: fonte do aparelho.</p><h3>O que a simulação representa</h3><p>Elipses resolvidas pela equação de Kepler, com excentricidade, inclinação, nodo e periastro. Todos os planetas compartilham o mesmo tempo. Vênus gira ao contrário; Urano tem eixo muito inclinado; Tritão orbita em sentido retrógrado.</p><p>Tamanhos e distâncias são ampliados por regras separadas. Órbitas lunares usam períodos e excentricidades aproximados, com fases iniciais ilustrativas e planos simplificados. Não há perturbações, eclipses calculados, precessão ou previsão do céu atual. A rotação em velocidades altas pode parecer lenta ou invertida por amostragem entre quadros: diminua a velocidade para observar.</p><h3>Seu progresso é seu</h3><p>O jogo guarda apenas visitas, respostas, velocidades experimentadas e preferências no localStorage. Não usa servidor de dados nem ferramentas de análise de visitantes. Ao abrir links de fontes, você sai do jogo.</p><p className="credits-signoff">Feito para pequenos exploradores com grandes perguntas. ✦</p></div></Modal>;
}
